Less intrusive import error handling
elementary/music pull request #604
Opened 2020-09-25 09:56 UTC by jeremypw

Fixes #470 

 - [x] Use toast for initial warning with button to access more information
 - [x] Show summary of different types of errors found in dialog
 - [x] Button to open filemanager at library location
 - [ ] Provide setting to turn off warning
 
Ideally there should be an option to install missing plugin(s) but that will be left for a future PR.

2020-09-28 19:15 UTC, danrabbit commented
Hey thanks for working on this and trying to provide better error feedback here! I agree that offering to trash these files is probably not great and showing them in Files is probably more productive.

I'm not sure a toast is a good option for this since toasts automatically expire and an import may be a long-running operation where the user steps away from the computer. A dialog is probably still appropriate for errors, especially if there is an option to always ignore errors

There should probably be some secondary text that explains the implications of an import error. For example that these files won't appear or be playable in Music.

I'm not sure always showing the library is the most helpful here, especially if the import is being performed from a different folder. This button should probably say something like "Show Files" and open the import location. It should probably be in the primary action position in the dialog and not floating in the center of the dialog.

"Ignore" would probably be a better dismiss action since it makes it explicit that you're electing to take no action on this problem and not just that you're closing the window.

Regarding the checkbox, I wonder if we really need this feature. It sounds like the original issue is that the import error dialog is shown while performing an automatic import. We probably don't want this dialog to not appear when performing a manual import. Failing silently is probably not expected for explicit action. But in the case of an automatic library rescan, failing silently is probably not a big deal. So it might solve the problem to fail silently on automatic imports without adding this new setting

2020-09-28 19:27 UTC, danrabbit requested changes
Looking at some of the error messaging, it's not super clear what these things mean or what can be done about it and just listing the number of files doesn't really explain which files are causing issues. An error dialog should ideally help the user to address the problem.

For example if there is an "invalid uri" what does that mean to someone who is trying to listen to their music and how can they fix it?

If something "took too long to load" should they wait and try again? Could this issue be resolved with a better network connection? Why do we have a time limit on how long it takes to load something, shouldn't we just wait for it to load?

2020-09-28 19:27 UTC, danrabbit commented on src/LibraryWindow.vala
> +                    invalid_text = _("Invalid uri: %i").printf (invalid_files.size) + "\n";
It's probably not clear to most people what a "URI" means

2020-09-28 19:27 UTC, danrabbit commented on src/LibraryWindow.vala
> +                    busy_text = _("Already being used: %i").printf (busy_files.size) + "\n";
I'm not sure it's clear what this means. Already being used by who or what?

2020-09-28 19:27 UTC, danrabbit commented on src/LibraryWindow.vala
> +                    missing_plugin_text = _("Required gstreamer plugin not installed: %i").printf (missing_plugin_files.size) + "\n";
Gstreamer is a niche technical detail that probably doesn't mean anything to most people. Mentioning "codecs" might be a little more generally understandable, but maybe there's a better word for this too. Maybe something in the direction of "Additional software codecs are needed:"

2020-09-29 08:33 UTC, jeremypw commented
Thanks for a lot of useful points - I'll get to work on them.  With regard to replacing the toast, do you suggest launching the dialog directly or perhaps putting some kind of error warning icon into the headerbar or somewhere which launches the dialog when pressed (and then disappears)?

Where a file is reported as busy (probably very rare in practice) I am not sure how to find out why - unless it is in the original error message. I used my own (draft) error summaries instead of outputting each error message as received.  Is it worth providing access to the full error details?

2022-04-11 21:48 UTC, danrabbit commented
Closing since this targets old Music

2022-04-11 21:48 UTC, closed without merging